---
title: Tejas Viswanath
author: Tejas Viswanath
email: tejasviswa@gmail.com
description: Tejas Viswanath is a student
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
